# Lecture 6: Numpy 

<img src="numpy.gif" alt="numpy-logo" /> 

[The NumPy Reference](https://docs.scipy.org/doc/numpy/reference/).


### <left> <b> <span style="color:brown;"> Objective: </span> </b></left>

This lecture aims to introduce the core concepts of `NumPy`, a fundamental library for numerical computing in Python. We will explore how to create and manipulate multidimensional arrays, perform vectorized operations, and efficiently handle large datasets. By understanding these tools, you'll gain the ability to perform high-performance numerical computations and build the foundation for scientific computing and data analysis using `NumPy`.
****

## What is NumPy?


> **NumPy (Numerical Python)** is the core library for scientific computing in Python, that provide high-performance vector, matrix, and higher-dimensional data structures for Python. It is implemented in ``C`` and ``Fortran``. so when calculations are vectorized (formulated with vectors and matrices), the performance is very good. It provides a high-performance multidimensional array object, and tools for working with these arrays.


> This library can be used for different functions in **Linear algebra, Matrix computations, Fourier Transforms**. Alongside Numpy is most suitable for performing basic numerical computations such as *mean, median, range*, etc.

> It is an open source module of Python which provides fast mathematical computation on arrays and matrices. Since, arrays and matrices are an essential part of the Machine Learning ecosystem.

> ``Machine learning`` uses vectors, and in that regard, Numpy can be used in all common classes of problem in Machine Learning. Example: **Classification, Regressoin, Clustering** etc.



<img src="object.png" alt="Vlad's Home Directory" /> 

## NumPy arrays

At the core of the NumPy package, is the ``ndarray`` object. This encapsulates n-dimensional arrays of homogeneous data types, with many operations being performed in compiled code for performance.

  
  
  A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the *rank* of the array; the *shape* of an array is a tuple of integers giving the size of the array along each dimension.
  
  
  <img src=" 1d_array.png" alt="Vlad's Home Directory" /> 
  
Data manipulation in Python is nearly synonymous with NumPy array manipulation: even newer tools like Pandas are built around the NumPy array. This section will present several examples of using NumPy array manipulation to access data and subarrays, and to split, reshape, and join the arrays.   


There are a number of ways to initialize new numpy arrays, for example from

* a Python list or tuples;
* using functions that are dedicated to generating numpy arrays, such as arange, linspace, etc.;
* reading data from files.

### To use numpy you need to import the module

**Import conventions** : The recommended convention to import numpy is:

In [1]:
import numpy as np

### From lists
For example, to create new vector and matrix arrays from Python lists we can use the ``np.array`` function.

In [3]:
# a vector: the argument to the array function is a Python list
v = np.array([1,2,3,4])

v

array([1, 2, 3, 4])

In [5]:
a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)            # Prints "(3,)"
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]


In [25]:
b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

(2, 3)
1 2 4


In [27]:
b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape) 
print(b[1,1])
print(b)

(2, 3)
5
[[1 2 3]
 [4 5 6]]


In [31]:
b = np.array([[1,2,3],[4,5,6], [7,8,9]])    # Create a rank 2 array
print(b.shape)
print(b)

(3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Numpy also provides many functions to create arrays:

In [43]:
import numpy as np


print("-----------------------------------------------------------------------")

print("Evenly spaced: \n")

a1 = np.arange(10) # 0 .. n-1  (!). Evenly spaced.
print(a1)

print("\n")

b1 = np.arange(1, 9, 2) # start, end (exclusive), step. 
print(b1)


print("=========================================================================")

print("Spaced by number of points: \n")


c1 = np.linspace(0, 1, 6)   # start, end, num-points, linspace generate num-points evenly spaced btn 0 and 6
print(c1)


print("\n")

d1 = np.linspace(0, 1, 5, endpoint=False) # endpoint=False when you don't want the last number to be included
print(d1)



print("=========================================================================")
print("Common arrays: \n")


a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"
print("\n")
    
b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

print("\n")

c = np.full((2,2), 7)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"
print("\n")
    
d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"
print("\n")
    
e = np.random.random((2,2))  # Create an array filled with random values
print("E=",e)                     # Might print "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"

-----------------------------------------------------------------------
Evenly spaced: 

[0 1 2 3 4 5 6 7 8 9]


[1 3 5 7]
Spaced by number of points: 

[0.  0.2 0.4 0.6 0.8 1. ]


[0.  0.2 0.4 0.6 0.8]
Common arrays: 

[[0. 0.]
 [0. 0.]]


[[1. 1.]]


[[7 7]
 [7 7]]


[[1. 0.]
 [0. 1.]]


E= [[0.13861957 0.61117624]
 [0.06510725 0.59081978]]


In [53]:
g = np.linspace(1,10,4)
g

array([ 1.,  4.,  7., 10.])

You can read about other methods of array creation [in the documentation](https://docs.scipy.org/doc/numpy/user/basics.creation.html#arrays-creation).

* * * * 
Exercise: **Creating arrays using functions**

> Experiment with arange, linspace, ones, zeros, eye and diag.
    Create different kinds of arrays with random numbers.
    Try setting the seed before creating an array with random values.
    Look at the function np.empty. What does it do? When might this be useful?

* * * * 

### NumPy Array Attributes

Each array has attributes ``ndim`` (the number of dimensions), ``shape`` (the size of each dimension), and ``size`` (the total size of the array):

In [77]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size= 6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array


In [85]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)
x3

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

### Basic data types

Different data-types allow us to store data more compactly in memory, but most of the time we simply work with floating point numbers. Note that, in the example above, NumPy auto-detects the data-type from the input.

In [89]:
a = np.array([1, 2, 3])
print(a.dtype)


b = np.array([1., 2., 3.])
print(b.dtype)


int64
float64


You can explicitly specify which data-type you want:

In [97]:
c = np.array([1, 2, 3], dtype=float)
print(c.dtype)
c

float64


array([1., 2., 3.])

In [95]:
c = np.array([1, 2, 3], dtype=np.int16)
print(c.dtype)
c

int16


array([1, 2, 3], dtype=int16)

Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. Here is a more example:

In [11]:
import numpy as np

x = np.array([1, 2])   # Let numpy choose the datatype
print(x.dtype)         # Prints "int64"

x = np.array([1.0, 2.0])   # Let numpy choose the datatype
print(x.dtype)             # Prints "float64"

x = np.array([1, 2], dtype=np.int64)   # Force a particular datatype
print(x.dtype)                         # Prints "int64"


int64
float64
int64


You can read all about numpy datatypes [in the documentation](https://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html).

### **What is the default data type ?**

There are also other types:
    
 <img src="types.png" alt="Vlad's Home Directory" /> 
    

## Array Indexing: Accessing Elements/Subarrays


Numpy offers several ways to index into arrays.

**Slicing**: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:



In [99]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]

print(a)

print('--------------------------------------------------------------------------')

print(b)

print('--------------------------------------------------------------------------')


# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"

print('--------------------------------------------------------------------------')

b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
--------------------------------------------------------------------------
[[2 3]
 [6 7]]
--------------------------------------------------------------------------
2
--------------------------------------------------------------------------
77


In [123]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
b = a[:2, 1:3]
c = a[:, :3]
print(a)
print(b)
print(c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]


You can also mix integer indexing with slice indexing. However, doing so will yield an array of lower rank than the original array.

In [119]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"

print('--------------------------------------------------------------------------')


print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"

print('--------------------------------------------------------------------------')

print(col_r2, col_r2.shape)  # Prints "[[ 2]
                             #          [ 6]
                             #          [10]] (3, 1)"


[5 6 7 8] (4,)
--------------------------------------------------------------------------
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
--------------------------------------------------------------------------
[[ 2]
 [ 6]
 [10]] (3, 1)


In [129]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
row_r1 = a[1, :] 
row_r2 = a[1:2, :] 
print(a)
print(row_r1)
print(row_r1, row_r1.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[5 6 7 8]
[5 6 7 8] (4,)


### Reshaping of Arrays

Another useful type of operation is reshaping of arrays. The most flexible way of doing this is with the ``reshape`` method. For example, if you want to put the numbers 1 through 9 in a $3 \times 3$ grid, you can do the following:

In [131]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [145]:
grid = np.arange(1, 7).reshape((3, 2))
print(grid)

[[1 2]
 [3 4]
 [5 6]]


Note that for this to work, the size of the initial array must match the size of the reshaped array. Tyr a few examples that you will create.

### Fancy indexing

Fancy indexing is the name for when an array or a list is used in-place of an index:

In [15]:
twenty = (np.arange(4 * 5)).reshape(4, 5)
twenty

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [16]:
row_indices = [1, 2, 3]
twenty[row_indices]


array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [17]:
col_indices = [1, 2, -1] # remember, index -1 means the last element
twenty[row_indices, col_indices]

array([ 6, 12, 19])



We can also use index **masks**:

    If the index mask is a NumPy array of data type bool, then an element is selected (True) or not (False) depending on the value of the index mask at the position of each element



In [18]:
# 1D array of random integers
# get 10 integers from 0 to 23

num_samples = 10
integers = np.random.randint(23, size=num_samples)
integers

array([15, 20,  3, 12,  4, 20,  8, 14, 15, 20])

In [19]:
# mask has to be of the same shape as the array to be indexed; else IndexError would be thrown
# mask for indexing alternate elements in the array
row_mask = np.array([True, False, True, False, True, False, True, False, True, False])

integers[row_mask]

array([15,  3,  4,  8, 15])



This feature is very useful to conditionally select elements from an array, using for example comparison operators:


In [20]:
range_arr = np.arange(0, 10, 0.5)
range_arr

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [21]:
mask = (range_arr > 5) * (range_arr < 7.5)
mask
# What is happenning here?

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True, False, False, False,
       False, False])

In [22]:
range_arr[mask]

array([5.5, 6. , 6.5, 7. ])

* * * * 
### Exercise:
 > Investigate the **Concatenation, Splitting, Copies,repeat, tile, vstack, hstack**  functions for numpy arrays.
 
 > Investigate [Views versus copies in NumPy](https://scipy-cookbook.readthedocs.io/items/ViewsVsCopies.html)



* * * * 

## Array math

Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [23]:
import numpy as np

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))


[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


We instead use the ``dot`` function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. ``dot`` is available both as a function in the numpy module and as an instance method of array objects:

In [24]:
import numpy as np

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))

# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))


219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


Numpy provides many useful functions for performing computations on arrays; one of the most useful is ``sum``

In [25]:
import numpy as np

x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"


10
[4 6]
[3 7]


You can find the full list of mathematical functions provided by numpy [in the documentation](https://docs.scipy.org/doc/numpy/reference/routines.math.html).

## Vectorizing functions

As mentioned several times by now, to get good performance we should always try to avoid looping over elements in our vectors and matrices, and instead use vectorized algorithms. The first step in converting a scalar algorithm to a vectorized algorithm is to make sure that the functions we write work with vector inputs.

In [26]:
def Theta(x):
    """
    scalar implementation of the Heaviside step function.
    """
    if x >= 0:
        return 1
    else:
        return 0

In [27]:
v1 = np.array([-3,-2,-1,0,1,2,3])

Theta(v1)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()



That didn't work because we didn't write the function Theta so that it can handle a vector input...

To get a vectorized version of Theta we can use the Numpy function vectorize. In many cases it can automatically vectorize a function:


In [28]:
Theta_vec = np.vectorize(Theta)
Theta_vec(v1)

array([0, 0, 0, 1, 1, 1, 1])

On the Other Hand (OTHO), we can also implement the function to accept a vector input from the beginning (requires more effort but might give better performance):

In [29]:
def Theta(x):
    """
    Vector-aware implementation of the Heaviside step function.
    """
    return 1 * (x >= 0)

In [30]:
Theta(v1)

array([0, 0, 0, 1, 1, 1, 1])

In [31]:
# it even works with scalar input
Theta(-1.2), Theta(2.6)

(0, 1)

Numpy provides many more functions for manipulating arrays; you can see the full list [in the documentation](https://docs.scipy.org/doc/numpy/reference/routines.array-manipulation.html).

## Broadcasting

Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

<img src="broad.png" alt="Vlad's Home Directory" /> 

For example, suppose that we want to add a constant vector to each row of a matrix. We could do it like this:

In [32]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

# Now y is the following
# [[ 2  2  4]
#  [ 5  5  7]
#  [ 8  8 10]
#  [11 11 13]]
print(y)


[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


This works; however when the matrix ``x`` is very large, computing an explicit loop in Python could be slow. Note that adding the vector ``v ``to each row of the matrix ``x`` is equivalent to forming a matrix ``vv`` by stacking multiple copies of ``v`` vertically, then performing elementwise summation of ``x`` and ``vv``. We could implement this approach like this:

In [189]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))   # Stack 4 copies of v on top of each other
print(vv)                 # Prints "[[1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]]"
y = x + vv  # Add x and vv elementwise
print(y)  # Prints "[[ 2  2  4
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"


[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [183]:
import numpy as np
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4,2))   # Stack 4 copies of v on top of each other
print(vv)                

[[1 0 1 1 0 1]
 [1 0 1 1 0 1]
 [1 0 1 1 0 1]
 [1 0 1 1 0 1]]


In [193]:
y = np.array([[2,3,4],[5,6,7]])
z = np.array([2,0,9])
x = y+z
print(x)
j = np.tile(x,(3,2))
print(j)

[[ 4  3 13]
 [ 7  6 16]]
[[ 4  3 13  4  3 13]
 [ 7  6 16  7  6 16]
 [ 4  3 13  4  3 13]
 [ 7  6 16  7  6 16]
 [ 4  3 13  4  3 13]
 [ 7  6 16  7  6 16]]


Numpy broadcasting allows us to perform this computation without actually creating multiple copies of v. Consider this version, using broadcasting:

In [157]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(x)  # Prints "[[ 2  2  4]
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


The line ``y = x + v`` works even though ``x`` has shape **(4, 3)** and ``v`` has shape **(3,)** due to broadcasting; this line works as if ``v`` actually had shape **(4, 3)**, where each row was a copy of ``v``, and the sum was performed elementwise.

* * * * 

Broadcasting two arrays together follows these rules:


1. If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.
 
2. The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.
    
3. The arrays can be broadcast together if they are compatible in all dimensions.
    
4. After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
    
5. In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension


If this explanation does not make sense, try reading the explanation from the [documentation](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html)
Functions that support broadcasting are known as universal functions. You can find the list of all universal functions [in the documentation](https://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs).

Here are some applications of broadcasting:

In [159]:
import numpy as np

# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:
# [[ 4  5]
#  [ 8 10]
#  [12 15]]
print(np.reshape(v, (3, 1)) * w)

# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:
# [[2 4 6]
#  [5 7 9]]
print(x + v)

# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:
# [[ 5  6  7]
#  [ 9 10 11]]
print((x.T + w).T)
# Another solution is to reshape w to be a column vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x + np.reshape(w, (2, 1)))

# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
# [[ 2  4  6]
#  [ 8 10 12]]
print(x * 2)


[[ 4  5]
 [ 8 10]
 [12 15]]
[[2 4 6]
 [5 7 9]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 2  4  6]
 [ 8 10 12]]


# Practical_6 Exercises

### Exercise 1:
Create a NumPy array of integers from 1 to 10.

In [3]:
import numpy as np
print(np.arange(1,11))

[ 1  2  3  4  5  6  7  8  9 10]


### Exercise 2:
Create a 3x3 NumPy array filled with zeros.

In [6]:
a = np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.

In [41]:
b= np.linspace(0,5,10, endpoint = False)
print(b)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


### Exercise 4:
Create a 5x5 identity matrix using NumPy.

In [45]:
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.

In [423]:
#print(np.random.randint(1, size= (4,4)))

In [55]:
print(np.random.random((4,4)))

[[0.56114652 0.72969809 0.69562267 0.3264818 ]
 [0.16529393 0.44869276 0.35832495 0.59284777]
 [0.27618478 0.82114256 0.34115293 0.16533184]
 [0.48179152 0.28914938 0.82988532 0.89478105]]


In [61]:
print(np.random.rand(4,4))

[[0.09548775 0.80960822 0.78703582 0.16095406]
 [0.54981502 0.43389685 0.25950069 0.38288625]
 [0.16825435 0.3193486  0.17096654 0.43708812]
 [0.49722117 0.98052059 0.97917516 0.93971633]]


In [77]:
np.random.seed(10)

In [79]:
a = np.random.rand(4,4)
a

array([[0.77132064, 0.02075195, 0.63364823, 0.74880388],
       [0.49850701, 0.22479665, 0.19806286, 0.76053071],
       [0.16911084, 0.08833981, 0.68535982, 0.95339335],
       [0.00394827, 0.51219226, 0.81262096, 0.61252607]])

In [81]:
np.random.seed(0)
a= np.random.rand(4,4)
a

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

### Exercise 6:
Find the shape of a NumPy array.

In [39]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a.shape)

(3, 3)


### Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.

In [84]:
a.reshape((4,4))

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

### Exercise 8:
Find the data type of the elements in a NumPy array.

In [86]:
a.dtype

dtype('float64')

### Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.

In [94]:
c = np.arange(2,101,2)
c

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

### Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.

In [96]:
x = np.random.randint(10,50, size= (6,6))
x

array([[15, 25, 10, 28, 45, 34],
       [39, 29, 29, 24, 49, 42],
       [11, 19, 42, 41, 20, 33],
       [45, 21, 38, 44, 10, 10],
       [46, 15, 48, 27, 25, 14],
       [41, 11, 11, 49, 45, 48]])

### Exercise 11:
Slice a 2D NumPy array to extract a submatrix.

In [241]:
v = np.array([[2,3,4],[4,5,6],[6,7,8],[9,10,11]])
print(v)
print(v[:3, 1:3])
print(v.shape)

[[ 2  3  4]
 [ 4  5  6]
 [ 6  7  8]
 [ 9 10 11]]
[[3 4]
 [5 6]
 [7 8]]
(4, 3)


### Exercise 12:
Calculate the sum of all elements in a NumPy array.

In [103]:
np.sum(v)

75

### Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.

In [105]:
np.mean(v)

6.25

In [109]:
np.std(v)

2.7118566825454966

In [111]:
np.median(v)

6.0

### Exercise 14:
Find the maximum and minimum values in a NumPy array.

In [115]:
print(np.max(v))
print(np.min(v))

11
2


### Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.

In [181]:
f = np.random.randint(1,21, (5,4))
d= np.max(f)
print(f)
print(d)
print(np.argmax(f))

[[ 7 18  8  3]
 [17 19 14  5]
 [ 5 13 18  2]
 [ 6  2 20 20]
 [ 8 10 18 10]]
20
14


### Exercise 16:
Create a NumPy array and reverse its elements.

In [163]:
g = f[::-1]
g

array([[ 2, 13,  4, 19],
       [16, 12,  7, 16],
       [16, 10, 19,  9],
       [ 5,  7, 14,  8],
       [20,  2,  9,  1]])

### Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.

In [191]:
s= np.array([[1,2,3],[3,4,5],[5,6,7]])
t = np.array([[98,21,3],[2,33,45],[1,5,2]])
m = np.multiply(s,t)
print(m)

[[ 98  42   9]
 [  6 132 225]
 [  5  30  14]]


### Exercise 18:
Create a diagonal matrix from a given 1D array.

In [215]:
print(np.diag(s))
print(np.diag(m))

[1 4 7]
[ 98 132  14]


### Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.

In [245]:
k= np.array([ [1,2], [1,2] ])

In [247]:
n= np.array([ [4,5], [6,7] ])

In [249]:
print(k*n)

[[ 4 10]
 [ 6 14]]


In [443]:
print(np.dot(k,n))

[[16 19]
 [16 19]]


In [227]:
np.array([1,2]).shape

(2,)

In [237]:
np.array([ [[1,2, 3], [1,2, 3]], [[1,2, 3], [1,2, 3]] ]).shape

(2, 2, 3)

In [243]:
j= np.array([ [ [1,2, 3], [1,2, 3] ], [ [1,2, 3], [1,2, 3] ] ])
print(j.ndim)

3


### Exercise 20:
Flatten a 2D NumPy array into a 1D array.

In [256]:
print(k.flatten())

[1 2 1 2]


### Exercise 21:
Stack two NumPy arrays vertically.

In [271]:
print(np.vstack((k,n)))

[[1 2]
 [1 2]
 [4 5]
 [6 7]]


array([[1, 2],
       [1, 2],
       [4, 5],
       [6, 7]])

### Exercise 22:
Stack two NumPy arrays horizontally.

In [269]:
print(np.hstack((k,n)))

[[1 2 4 5]
 [1 2 6 7]]


### Exercise 23:
Split a NumPy array into multiple sub-arrays.

In [273]:
print(np.split(k,2))

[array([[1, 2]]), array([[1, 2]])]


### Exercise 24:
Generate a random NumPy array and round each element to two decimal places.

In [295]:
a= np.linspace(1,21,10)
print(np.round(a,decimals =2))

[ 1.    3.22  5.44  7.67  9.89 12.11 14.33 16.56 18.78 21.  ]


### Exercise 25:
Find the unique elements of a NumPy array.

In [305]:
t = np.array([[1,6,3],[3,4,2]])
print(np.unique(t))

[1 2 3 4 6]


### Exercise 26:
Replace all elements in a NumPy array that are less than a specific value with that value.

In [308]:
print(np.where(t<3,0,t))

[[0 6 3]
 [3 4 0]]


### Exercise 27:
Find the cumulative sum of the elements in a NumPy array.

In [310]:
print(np.cumsum(t))

[ 1  7 10 13 17 19]


### Exercise 28:
Create a NumPy array and find the number of non-zero elements in it.

In [314]:
print(np.nonzero(n))

(array([0, 0, 1, 1]), array([0, 1, 0, 1]))


### Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.

In [329]:
h = np.random.randint(1,21, (4,5))
h

array([[20,  5, 18, 17,  4],
       [11,  2,  5,  5, 17],
       [17, 16, 11, 14,  9],
       [12,  7, 10, 16,  4]])

### Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.

In [343]:
print(np.sum(s, axis=1))
print(np.sum(s,axis=0))

[ 6 12 18]
[ 9 12 15]


### Exercise 31:
Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).

In [349]:
d = np.array([[1, 2], [3, 4],  
                 [5, 1], [0, 1]]) 
print((d-np.min(d))/(np.max(d)-np.min(d))) 
# d.shape

[[0.2 0.4]
 [0.6 0.8]
 [1.  0.2]
 [0.  0.2]]


### Exercise 32:
Create two NumPy arrays and find the dot product.

In [353]:
print(np.dot(k,n))

[[16 19]
 [16 19]]


### Exercise 33:
Find the trace of a square NumPy matrix.

In [355]:
print(np.trace(t))

5


### Exercise 34:
Create a 2D array and swap two rows.

In [361]:
o = np.array([ [23,45,90], [56,67,89], [23,56,98] ])
print(np.roll(o,2, axis=0))

[[56 67 89]
 [23 56 98]
 [23 45 90]]


### Exercise 35:
Create a 1D NumPy array and convert it into a column vector.

In [377]:
p = np.array([1,2,3,4,5])
print(p[:,None])

[[1]
 [2]
 [3]
 [4]
 [5]]


### Exercise 36:
Find the determinant of a 3x3 matrix.

In [381]:
print(np.linalg.det(s))

2.042810365310277e-15


### Exercise 37:
Find the eigenvalues and eigenvectors of a 2x2 matrix.

In [385]:
mn = np.array([[1, 2], 
              [2, 3]]) 
print(np.linalg.eig(mn))

EigResult(eigenvalues=array([-0.23606798,  4.23606798]), eigenvectors=array([[-0.85065081, -0.52573111],
       [ 0.52573111, -0.85065081]]))


### Exercise 38:
Solve a system of linear equations using NumPy.

In [387]:
l = np.array([ [1,2], [3,4] ])
f = np.array([7,8])
print(np.linalg.solve(l,f))

[-6.   6.5]


### Exercise 39:
Add Gaussian noise to a NumPy array.

In [395]:
noise = np.random.normal(0,1, len(l))
p= noise + l
p

array([[1.02212126, 1.67871349],
       [3.02212126, 3.67871349]])

### Exercise 40:
Create a 4x4 matrix and extract the diagonal elements.

In [407]:
w = np.arange(1,17).reshape((4,4))
print(w)
print(np.diag(w))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[ 1  6 11 16]


### Exercise 41:
Generate a NumPy array of 100 random values and clip the values to a range between 10 and 50.

In [425]:
h = np.arange(1,101)
print(np.clip(h,10,50))

[10 10 10 10 10 10 10 10 10 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50
 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50
 50 50 50 50]


### Exercise 42:
Create a 2D NumPy array and replace all negative values with zero.

In [431]:
j = np.array([ [-2,3,4], [0,-9,2] ])
print(np.where(j<0,0,j))

[[0 3 4]
 [0 0 2]]


### Exercise 43:
Find the inner and outer products of two NumPy arrays.

In [433]:
print(np.outer(s,n))

[[ 4  5  6  7]
 [ 8 10 12 14]
 [12 15 18 21]
 [12 15 18 21]
 [16 20 24 28]
 [20 25 30 35]
 [20 25 30 35]
 [24 30 36 42]
 [28 35 42 49]]


In [437]:
print(np.inner(s,t))

[[22 17]
 [42 35]
 [62 53]]


### Exercise 44:
Calculate the pairwise distances between points in a NumPy array.

In [439]:
x = np.array((1, 2, 3))
y = np.array((4,5, 6))
z = np.linalg.norm(x - y)
print(z)

5.196152422706632


### Exercise 45:
Create a structured NumPy array with fields for `name`, `age`, and `height`.

In [445]:
dtype = [('name', 'U10'), ('age', 'i4'), ('height', 'f4')]
my_array = np.array([
    ('Peter', 25, 5.5),
    ('Aline', 30, 5.8),
    ('Zena', 35, 6.1),
    ('Eddy', 40, 5.9),
    ('Laura', 28, 5.7)
], dtype=dtype)
print(my_array)

[('Peter', 25, 5.5) ('Aline', 30, 5.8) ('Zena', 35, 6.1) ('Eddy', 40, 5.9)
 ('Laura', 28, 5.7)]


### Exercise 46:
Create a 5x5 matrix of random integers and count the occurrences of each unique value.

```python
# Exercise 46
```

---

### Exercise 47:
Generate a random 3x3 NumPy array and subtract the mean of each row from the corresponding row.

```python
# Exercise 47
```

---

### Exercise 48:
Create a NumPy array of random integers and check if any of the values are greater than 50.

```python
# Exercise 48
```

---

### Exercise 49:
Calculate the moving average of a 1D NumPy array.

```python
# Exercise 49
```

---

### Exercise 50:
Find the Pearson correlation coefficient between two NumPy arrays.

```python
# Exercise 50
```

---

### Exercise 51:
Convert a NumPy array of radians to degrees.

```python
# Exercise 51
```

---

### Exercise 52:
Create a random NumPy array and compute its variance and standard deviation.

```python
# Exercise 52
```

---

### Exercise 53:
Create a 2D NumPy array and find the indices of the maximum values along each axis.

```python
# Exercise 53
```

---

### Exercise 54:
Compute the inverse of a 2x2 NumPy matrix.

```python
# Exercise 54
```

---

### Exercise 55:
Create a NumPy array of 10 random values and standardize it (mean 0, variance 1).

```python
# Exercise 55
```

---

### Exercise 56:
Perform element-wise addition and subtraction on two NumPy arrays.

```python
# Exercise 56
```

---

### Exercise 57:
Create a NumPy array of random values and find the maximum element's index.

```python
# Exercise 57
```

---

### Exercise 58:
Create a 3x3 NumPy array and rotate it by 90 degrees.

```python
# Exercise 58
```

---

### Exercise 59:
Compute the Frobenius norm of a matrix.

```python
# Exercise 59
```

---

### Exercise 60:
Create a 3D NumPy array and slice out a subarray.

```python
# Exercise 60
```

---